# Generated by Django 4.2.6 on 2023-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_listens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listens',
            name='date',
            field=models.DateField(verbose_name='rating date'),
        ),
    ]
