# Generated by Django 4.2.6 on 2023-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_listens_options_alter_listens_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listens',
            name='date',
            field=models.DateField(verbose_name='Listens date'),
        ),
    ]
