# Generated by Django 4.2.6 on 2023-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_listens_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turntable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='listens',
            name='date',
            field=models.DateField(verbose_name='Listens Date'),
        ),
        migrations.AddField(
            model_name='vinyl',
            name='turntable',
            field=models.ManyToManyField(to='main_app.turntable'),
        ),
    ]
