# Generated by Django 4.2.6 on 2023-11-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='turntable',
            new_name='turntables',
        ),
    ]
